"""Observability helpers for the API server."""

from router_maestro.server.observability.metrics import (
    API_KIND_ADMIN,
    API_KIND_ANTHROPIC_COUNT_TOKENS,
    API_KIND_ANTHROPIC_MESSAGES,
    API_KIND_ANTHROPIC_MODELS,
    API_KIND_GEMINI_COUNT_TOKENS,
    API_KIND_GEMINI_GENERATE,
    API_KIND_GEMINI_STREAM,
    API_KIND_OPENAI_CHAT,
    API_KIND_OPENAI_MODELS,
    API_KIND_OPENAI_RESPONSES,
    API_KINDS,
    BOOL_LABEL_FALSE,
    BOOL_LABEL_TRUE,
    CONTENT_TYPE_LATEST,
    HTTP_DURATION_BUCKETS,
    HTTP_REQUEST_DURATION_SECONDS,
    HTTP_REQUESTS_TOTAL,
    METRIC_PREFIX,
    UNMATCHED_ROUTE_PATH_TEMPLATE,
    HttpMetrics,
    bool_label,
    create_http_metrics,
    create_registry,
    path_template_from_scope,
    render_metrics,
)

__all__ = [
    "API_KIND_ADMIN",
    "API_KIND_ANTHROPIC_COUNT_TOKENS",
    "API_KIND_ANTHROPIC_MESSAGES",
    "API_KIND_ANTHROPIC_MODELS",
    "API_KIND_GEMINI_COUNT_TOKENS",
    "API_KIND_GEMINI_GENERATE",
    "API_KIND_GEMINI_STREAM",
    "API_KIND_OPENAI_CHAT",
    "API_KIND_OPENAI_MODELS",
    "API_KIND_OPENAI_RESPONSES",
    "API_KINDS",
    "BOOL_LABEL_FALSE",
    "BOOL_LABEL_TRUE",
    "CONTENT_TYPE_LATEST",
    "HTTP_DURATION_BUCKETS",
    "HTTP_REQUEST_DURATION_SECONDS",
    "HTTP_REQUESTS_TOTAL",
    "METRIC_PREFIX",
    "UNMATCHED_ROUTE_PATH_TEMPLATE",
    "HttpMetrics",
    "bool_label",
    "create_http_metrics",
    "create_registry",
    "path_template_from_scope",
    "render_metrics",
]
